server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:payment-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      client:
        config:
          order:
            connectTimeout: 3000
            readTimeout: 5000
          shopping-store:
            connectTimeout: 3000
            readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    ru.yandex.practicum.commerce.payment: INFO
