spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smarthome}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true

app:
  kafka:
    groups:
      snapshots: ${KAFKA_GROUP_SNAPSHOTS:analyzer-snapshots}
      hubs: ${KAFKA_GROUP_HUBS:analyzer-hubs}
    topics:
      snapshots: ${KAFKA_TOPIC_SNAPSHOTS:telemetry.snapshots.v1}
      hubs: ${KAFKA_TOPIC_HUBS:telemetry.hubs.v1}

grpc:
  client:
    hub-router:
      address: "static://${HUB_ROUTER_ADDR:localhost:59090}"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
